Repository fityannugroho/idn-area, pull requests merged in 2023-10, with the labels that each got.

#197 Check code formatting on PR or push to `main`
  .github/workflows/pr-tests.yml
  .github/workflows/tests.yml
  CONTRIBUTING.md
  package.json
Labels: enhancement

#198 Update README API docs sections
  README.md
Labels: documentation

#194 Added Hindi translation of README.md (hindi reviewers requested)
  docs/README_hi.md
Labels: help wanted
